### ISSUE TITLE
How alink Operator rely on  flink job execution?

### ISSUE THREAD

**Issue by rejector7** [alibaba/Alink#175]
I meet a problem.

![01](https://user-images.githubusercontent.com/20394580/122545115-0f79a400-d060-11eb-966d-3bd81d377d6e.jpg)
![02](https://user-images.githubusercontent.com/20394580/122552375-d42fa300-d068-11eb-802f-83124577da02.jpg)

The computer has alink 1.4 and pyflink 1.13 and flink 1.10.

When I run alink programs, it runs into a classnotfound exception. 
In my view, it is a jar confliction. The case is as below.
it won't call the jars in pyflink.
The job would be executed in flink 1.10(it is launched beforehand）.
So the classpath or memory somewhere has flink1.10, and alink choose flink1.10, not pyflink1.13.

I wanna know how the alink make the decision about which flink to choose, and what is the procedure?

**Comment by Fanoid** [comment]
Hi, are you upgrading from PyAlink previous release to 1.4.0?
If so, I think you just encountered a bug of PyFlink, because they lately split PyFlink package to apache-flink and apache-flink-libraries in its 1.13 releases.
Please reinstall using `pip install -U apache-flink==1.13.0 apache-flink-libraries==1.13.0` manually.
